JordoUserBundle:
    resource: "@JordoUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@JordoUserBundle/Resources/config/routing.yml"

JordoCoreBundle:
    resource: "@JordoCoreBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
